### ISSUE TITLE
Browser freezing when cloning big repo

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#292]
We discuss on gitter with @burningTyger about perfomence of Big repos, his was not working in electron (20MB) and mine was freezing (15MB) the browser tab (right click was not working) before I get message:
```
Counting objects: 12462, done.
Compressing objects: 100% (24/24), done.
Total 12462 (delta 28), reused 28 (delta 17), pack-reused 12421
```
next I've needed to wait a bit, but at least I could open dev tools and pause the script. It was not possible before emitter send messages. And the clone was successful (I'm using full clone right now).

the version is from unpkg.org CDN with 0.x.x

**Comment by wmhilton** [comment]
Yup, JavaScript is single threaded, unzipping a big packfile uses 100% CPU and runs synchronously at the moment.

We need to figure out how to make it happen in little chunks so it doesn't hog the thread from the UI. The workaround use then is to wrap isomorphic-git in a WebWorker.

**Comment by wmhilton** [comment]
By coincidence, I discovered #294 today which would also speed up cloning tremendously.

**Comment by jcubic** [comment]
Thanks will use worker then. I'm reading the source for workerize https://github.com/developit/workerize/blob/master/src/index.js that create worker from function or string and allow to execute functions from outside maybe I will cam up with worker version of isomorphic-git.

**Comment by jcubic** [comment]
There is open issue in webpack about this https://github.com/webpack/webpack/issues/6525 I think that rollup is creating correct UMD for browser and worker.

Maybe just using self instead of window will fix the issue since we only care about browsers anyway.
they suggest `output.globalObject: "this"` in webpack config.

**Comment by wmhilton** [comment]
I've often had luck shimming window in a worker. Something like this

```
window = self
importScript('https://unpkg.com/isomorphic-git@0.19.6/dist/bundle.umd.min.js')
```

would probably work. If not, making an official Worker wrapper is coming up on my todo list anyway. :)

**Comment by jcubic** [comment]
Is it possible to show some kind of progress or messages what are being done, between calling the clone function and current messages?

**Comment by jcubic** [comment]
The problem with web worker and BrowserFS is that the fs is not in sync and need to be reconfigured on each command in web worker message and in response message.

One issue is that in memory directory will not work because it's rewritten when calling configure after web worker finish. Because BrowserFS need to be recreated after the command it will be impossible to do this because isomorphic git just accept fs as dependency and know nothing about BrowserFS configure.

For reference here is my branch with the code for web worker (right now git clone call function from worker wrapper) https://github.com/jcubic/git/compare/gh-pages...git-worker?expand=1

**Comment by wmhilton** [comment]
It's entirely possible. You need to put the fs AND git behind a dedicated webworker. I did it here https://github.com/wmhilton/wills-wonderful-service-worker/blob/master/src/index.js

**Comment by jcubic** [comment]
Web worker is much easier to manage then service worker.

**Comment by jcubic** [comment]
I've didn't use service worker but web worker so it's created per user and killed when app is closed.

**Comment by wmhilton** [comment]
Oh hey... totally slipped my mind when I merged it with a blasé commit message, but #305 should solve this! The new parser that replaces `git-list-pack` (which parsed the entire packfile synchronously) is written to parse the file asynchronously in chunks, so the browser shouldn't freeze during cloning now. (I tested it with the https://isomorphic-git.github.io/docs/browser.html page and noticed a couple brief pauses. It's not silky smooth 60 FPS perfection yet but it's not bad.)

**Comment by wmhilton** [comment]
@jcubic Have you already worker-ified GIT Web Terminal? If so, you probably can't really test whether this is "fixed" from your perspective. :/ But if you haven't yet, then let me know if this addressed the browser freezing issues you encountered!

**Comment by jcubic** [comment]
I've replaced the worker call with normal git to test this and it still freezing the browser. I've got pause before messages that was not freezing then got messages then it frozen for a few seconds then unfroze and it finish.

**Comment by wmhilton** [comment]
Thank you for testing it! I've tested it by clicking the "Run" button on the [clone API docs page](https://isomorphic-git.github.io/docs/clone.html) and right-clicking the page a bunch, and you are right that there is apparently still a stage that is blocking. But for me it was only a brief segment near the beginning. I'm going to call this a partial victory.

Ultimately, while smooth performance in the main thread is a nice-to-have, I think any serious application of git in the browser will want to run clone & friends in a WebWorker to take advantage of a second computing core that's not competing with the main thread and DOM rendering for CPU time. Since even mobile devices have multiple cores, I think that is a reasonable assumption.

I like your worker implementation (I'm looking at https://github.com/jcubic/git/blob/git-worker/js/git-worker.js). It looks very similar to [workerize-loader](https://github.com/developit/workerize-loader/blob/master/src/rpc-worker-loader.js) which by coincidence I was studying carefully yesterday.

Something I'm considering in the "William finally decides to make a backwards incompatible change release" is ditching the event emitter parameter for a global subscription-based model. Something like:

```js
import { core, clone } from 'isomorphic-git';

// Configuration - done once in the WebWorker
core.fs = BrowserFS.BFSRequire('fs')
core.corsProxy = 'https://cors-buster-tbgktfqyku.now.sh/'
core.events.on('download::progress', console.log)
core.events.on('indexPack::progress', console.log)
core.events.on('checkout::progress', console.log)

// Usage functions - uses pure JSON arguments suitable for RPC calls
clone({
  dir: '.',
  url: 'https://github.com/isomorphic-git/isomorphic-git'
  singleBranch: true,
  depth: 1,
  rpcId: 123
})
```

Of course, there would be a catch-all subscription option, so you can simply forward ALL events from `core.events` to `postMessage`. And you can pass a special `rpcId` parameter to functions which will be included in all events emitted by that particular function call, so you can match up events from the global EventEmitter like:

```
let id = Math.floor(Math.random()*1000000000)
clone({ ..., rpcId: id })
core.events.on('*', (data) => {
  if (data.rpcId === id) {
    console.log(`I just care about this call ${data.progress}`)
  }
})
```

**Comment by jcubic** [comment]
I first searched for existed solution and I've remembered that [Jason Miller](https://github.com/developit) had library that created worker from function or string my code is based on that but on original standalone workerize. I've only unwrapped the code to have two event listeners he's implementation have only one and used on both worker and main thread.

And `core.events.on('*::message', console.log)`

will show messages for every command, I like this idea for my code, but what about having both global events and local one that way you will not be breaking change. You can just remove it from docs but keep the parameter, so you will call trigger/emit for local emitter if exists and always for global emitter.

if you will change how events function I would like to have one feature, parameter that indicate that the message is update of existing message, right now I'm using regex to detect if message is first message or need to printed  or updated for instance pull is using regex /^Compressing/ and it will break of more then one messsage have % in it. Maybe I just need to check if first word is the same as the prevoius one and it have %, but parameter would make life easier.

**Comment by wmhilton** [comment]
I *think* I'm emitting the raw progress messages, so the messages that "replace" a previous one should in fact include a carriage return at the beginning.

Oh never mind. https://github.com/isomorphic-git/isomorphic-git/blob/master/src/commands/fetch.js#L74 I'm "helpfully" trimming and normalizing the newlines for you. 🤦‍♂️

**Comment by jcubic** [comment]
\r at the beginning of the message would be as good as parameter I could just use:
```javascript
if (message[0] == '\r') {
    term.update(message);
} else {
   term.echo(message);
}
```
also I can add feature to jQuery Terminal that if string have \r at the beginning it will update lines from the end, didn't thought about this.

but I think that I can live without this feature, I can just use:

```javascript
function makeEmitter() {
  var emitter = new EventEmitter();
  var prev;
  emitter.on('message', function(message) {
    if (message.replace(/[0-9%]+/g, '') === prev) {
       term.update(message);
    } else {
       term.echo(message);
    }
    prev = message;
  });
  return emitter;
}
```
