### ISSUE TITLE
CORS with Gogs: missing token 'user-agent' in CORS header 'Access-Control-Allow-Headers'

### ISSUE THREAD

**Issue by MoonCoral** [isomorphic-git/isomorphic-git#555]
In the browser using the npm package with webpack I get:

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/BrokenWorld/Editor.git/info/refs?service=git-upload-pack. (Reason: missing token 'user-agent' in CORS header 'Access-Control-Allow-Headers' from CORS preflight channel).```

when executing
```js
//Actual strings substituted
git.clone({
    username: "Name",
    password: "Pass",
    url: "http://localhost:8000/Path/Path.git",
    dir: "/Path/Path"
});
```
The git server is Gogs and CORS is set up there. The http headers sent and received are below:
```
Response headers (441 B)
Access-Control-Allow-Headers:   Content-Type, Authorization
Access-Control-Allow-Origin:    http://localhost:8080
Access-Control-Max-Age:         3600
Content-Length:                 0
Date:                           Mon, 05 Nov 2018 16:39:32 GMT
Set-Cookie:                     lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie:                     i_like_gogits=3998a94c1759e12f; Path=/; HttpOnly
Set-Cookie:                     _csrf=TXDUIIY-1eQjYbUr9PHNZgsV…v 2018 16:39:32 GMT; HttpOnly
```

```
Request headers (477 B)	
Accept:                         text/html,application/xhtml+xm…plication/xml;q=0.9,*/*;q=0.8
Accept-Encoding:            	gzip, deflate
Accept-Language:	        en-US,en;q=0.5
Access-Control-Request-Headers:	authorization,user-agent
Access-Control-Request-Method:	GET
Connection:	                keep-alive
DNT:	                        1
Host:	                        localhost:8000
Origin:	                        http://localhost:8080
User-Agent:	                Mozilla/5.0 (X11; Linux x86_64…) Gecko/20100101 Firefox/60.0
```

(Setting Access-Control-Allow-Origin to * in Gogs doesn't change the error.)

What am I missing?

**Comment by wmhilton** [comment]
Shucks. I'm guessing that #247 (added in June) broke Gogs support (added in April).

I'll try to fix this upstream here: https://github.com/gogs/gogs/pull/5498

Meanwhile... we need a way to disable sending a User-Agent header. Ideally without:
- breaking the ability to clone gists
- adding an extra round-trip request using "OPTIONS" and manually inspecting the Allowed-Headers list because that would double the number of HTTP requests for every operation.
- adding a `disableUserAgentHeader` parameter to `fetch`, `push`, and `pull`, because then we'll eventually need a `disableXHeader` for every possible header

Lemme brainstorm this some.

**Comment by wmhilton** [comment]
aaaaaaah, I can't even do 
- adding an extra round-trip request using "OPTIONS" and manually inspecting the Allowed-Headers list because that would double the number of HTTP requests for every operation.

because that would ONLY work if the server includes 'access-control-allow-headers' in the 'access-control-expose-headers' header. So under normal circumstances, it's not even possible for isomorphic-git to find out what headers are allowed. Hmm.

Gah, I'd much rather STOP sending User-Agent by default and tell users "if you're cloning Gists, specify a useragent manually using the new `headers` parameter that @juancampa so wonderfully added". But I would hate to break something that works. On the other hand, I've already accidentally broken something that worked (cloning from Gogs). Arrgh.

**Comment by wmhilton** [comment]
@MoonCoral which browser are you using by the way? It used to be that 'User-Agent' was a restricted CORS header so older browsers might be throwing an error that newer browsers don't.

Meanwhile, I should set up Gogs locally and test.

**Comment by wmhilton** [comment]
I can reproduce it with Firefox 62 and Gogs 0.11.66 on Windows. Chrome does _not_ throw an XHR error, presumably because of #259.

**Comment by wmhilton** [comment]
@MoonCoral That should fix it - let me know if it doesn't or if you run into any more problems! 😁

**Comment by MoonCoral** [comment]
I am using Firefox 63 on Linux Mint.

This doesn't fix it for me because `process.browser` is `undefined`. `process.platform` however is `"browser"` in my setup.

I believe `process` is provided by `browserfs` in my case. I don't know whether that is an oddity on my part or the normal case.

**Comment by MoonCoral** [comment]
@wmhilton I believe this issue needs to be reopened.

**Comment by wmhilton** [comment]
Just curious, why are you using the `process` module from browserfs instead of the regular Webpack `process` module?

**Comment by wmhilton** [comment]
@MoonCoral as a temporary fix, what happens if you do
```js
process.browser = true
```
before you call isomorphic-git?

**Comment by wmhilton** [comment]
> I don't know whether that is an oddity on my part or the normal case.

It's a bit of an oddity, but since I recommend using BrowserFS with this module, and the BrowserFS documentation recommends using their version of `process`, it makes perfect sense. I want `isomorphic-git` to work for everyone. Especially if their setup is a result of simply "following the directions on the box", I want it to work.

**Comment by MoonCoral** [comment]
Adding `process.browser = true` before the first call to isomorphic-git fixes the issue for me.
Thank you.

**Comment by wmhilton** [comment]
> Adding process.browser = true before the first call to isomorphic-git fixes the issue for me.

Awesome. So that means I just need a better detection method for browsers. I'll try something that doesn't involve `process`. :)

**Comment by wmhilton** [comment]
I think I'll use the [browser-or-node](https://github.com/flexdinesh/browser-or-node) module. It's very lightweight, and seems to have been tested with several bundlers and with React Native too ([source](https://github.com/flexdinesh/browser-or-node/pull/2))

**Comment by MoonCoral** [comment]
I'm sorry to tell you but _browser-or-node_ seems to get also confused by _browserfs_ as it uses `process` to determine `isNode`...

Replacing `isNode` (locally in the installed package) by `!isBrowser` makes it work for me as `isBrowser` derives from `window` which is as one would expect in a browser.

**Comment by wmhilton** [comment]
Oh wow. bfs-process literally claims to be Node version "5.0".

I'm just worried that checks based on "window" will fail in JSDOM environment. I guess it's better to error on the side of not sending a User-Agent though.

**Comment by wmhilton** [comment]
How about now? :)

**Comment by MoonCoral** [comment]
Works like a charm. Thank you and apologies for the late feedback.
